global using Application;
global using DiServiceInstaller;
global using Domain.Errors;
global using Domain.ValueObjects;
global using Mapster;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Persistence;
global using Resulver.AspNetCore.WebApi;
global using Resulver.AspNetCore.WebApi.Response;
global using static Microsoft.AspNetCore.Http.StatusCodes;